#ifndef ONTOLOGY_H_
#define ONTOLOGY_H_
#include "project-conf.h"

const char * ontology = "{\n"
                        "  \"@context\": {\n"
                        "    \"owl\": \"http://www.w3.org/2002/07/owl#\",\n"
                        "    \"rdf\": \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\",\n"
                        "    \"rdfs\": \"http://www.w3.org/2000/01/rdf-schema#\",\n"
                        "    \"xsd\": \"http://www.w3.org/2001/XMLSchema#\",\n"
                        "    \"base\": \"https://www.cs.uni-potsdam.de/bs/research/myno#\",\n"
                        "    \"onem2m\": \"http://www.onem2m.org/ontology/Base_Ontology/base_ontology#\"\n"
                        "  },\n"
                        "  \"@graph\": [\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:Command\",\n"
                        "      \"@type\": \"owl:Class\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:ControllingFunctionality\",\n"
                        "      \"@type\": \"owl:Class\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:Device\",\n"
                        "      \"@type\": \"owl:Class\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:MeasuringFunctionality\",\n"
                        "      \"@type\": \"owl:Class\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:Operation\",\n"
                        "      \"@type\": \"owl:Class\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:OperationInput\",\n"
                        "      \"@type\": \"owl:Class\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:OperationOutput\",\n"
                        "      \"@type\": \"owl:Class\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:OperationState\",\n"
                        "      \"@type\": \"owl:Class\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:OutputDataPoint\",\n"
                        "      \"@type\": \"owl:Class\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:Service\",\n"
                        "      \"@type\": \"owl:Class\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:ThingProperty\",\n"
                        "      \"@type\": \"owl:Class\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:exposesCommand\",\n"
                        "      \"@type\": \"owl:ObjectProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:exposesFunctionality\",\n"
                        "      \"@type\": \"owl:AnnotationProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:hasCommand\",\n"
                        "      \"@type\": \"owl:ObjectProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:hasDataRestriction_pattern\",\n"
                        "      \"@type\": \"owl:DatatypeProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:hasDataType\",\n"
                        "      \"@type\": \"owl:AnnotationProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:hasFunctionality\",\n"
                        "      \"@type\": \"owl:AnnotationProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:hasInput\",\n"
                        "      \"@type\": \"owl:ObjectProperty\",\n"
                        "      \"rdfs:range\": {\n"
                        "        \"@id\": \"onem2m:ThingProperty\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:hasOperation\",\n"
                        "      \"@type\": \"owl:ObjectProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:hasOperationState\",\n"
                        "      \"@type\": \"owl:ObjectProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:hasOutput\",\n"
                        "      \"@type\": \"owl:ObjectProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:hasOutputDataPoint\",\n"
                        "      \"@type\": \"owl:ObjectProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:hasService\",\n"
                        "      \"@type\": \"owl:ObjectProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:hasSubService\",\n"
                        "      \"@type\": \"owl:ObjectProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:hasThingProperty\",\n"
                        "      \"@type\": \"owl:ObjectProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"onem2m:hasValue\",\n"
                        "      \"@type\": \"owl:DatatypeProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"rdfs:ContainerMembershipProperty\",\n"
                        "      \"@type\": \"owl:Class\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"http://yang-netconf-mqtt\",\n"
                        "      \"@type\": \"owl:Ontology\",\n"
                        "      \"owl:imports\": [\n"
                        "        {\n"
                        "          \"@id\": \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"http://www.w3.org/2000/01/rdf-schema#\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"http://www.onem2m.org/ontology/Base_Ontology/base_ontology-v0_9_0\"\n"
                        "        }\n"
                        "      ]\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:YangDescription\",\n"
                        "      \"@type\": \"owl:Class\",\n"
                        "      \"rdfs:subClassOf\": {\n"
                        "        \"@id\": \"onem2m:ThingProperty\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:cmdGetDeviceToken\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Command\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:uuidInput\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:cmdPubUpdateImage\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Command\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": [\n"
                        "        {\n"
                        "          \"@id\": \"base:inputUpdateImage\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:uuidInput\"\n"
                        "        }\n"
                        "      ]\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:cmdPubUpdateManifest\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Command\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": [\n"
                        "        {\n"
                        "          \"@id\": \"base:input_1_AppId\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_2_LinkOffset\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_3_Hash\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_4_Size\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_5_Version\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_6_OldVersion\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_7_InnerSignature\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_8_DeviceNonce\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_9_OuterSignature\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:uuidInput\"\n"
                        "        }\n"
                        "      ]\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:cmdRelayOff\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Command\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:uuidInput\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:cmdRelayOn\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Command\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:uuidInput\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:descInputAppId\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"AnwendungsID der Zielplattform\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:descInputDeviceNonce\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"Input device nonce\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:descInputHash\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"Input Hash\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:descInputInnerSignature\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"inner signature\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:descInputLinkOffset\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"Input Link Offset\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:descInputOldVersion\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"old version\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:descInputOuterSignature\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"outer signature\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:descInputSeqManifest\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"Input for Manifest\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:descInputSize\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"Size\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:descInputUpdateImage\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"Update Image\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:descInputVersion\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"version\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:deviceCategory\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ThingProperty\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"SETUP-1\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:deviceDesc\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"MQTT-Device identified by UUID\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:deviceUuid\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ThingProperty\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataType\": {\n"
                        "        \"@id\": \"xsd:string\"\n"
                        "      },\n"
                        "      \"onem2m:hasValue\": \"%s\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:funcDescGetDeviceToken\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"Get Token for MYNO Update\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:funcDescMoist\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"Get Moisture of Sensor\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:funcDescPubUpdateImage\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"Publish Update Image\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:funcDescPubUpdateManifest\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"Publish Update Manifest to Device\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:funcDescRelayOff\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"Relay anschalten\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:funcDescRelayOn\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"Relay ausschalten\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:funcDescTemperature\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"Reads the Temperature from the enviroment\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:funcGetDeviceToken\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ControllingFunctionality\"\n"
                        "      ],\n"
                        "      \"onem2m:hasCommand\": {\n"
                        "        \"@id\": \"base:cmdGetDeviceToken\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:funcDescGetDeviceToken\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:funcGetMoisture\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:MeasuringFunctionality\"\n"
                        "      ],\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:funcDescMoist\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:funcGetTemperature\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:MeasuringFunctionality\"\n"
                        "      ],\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:funcDescTemperature\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:funcPubUpdateImage\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ControllingFunctionality\"\n"
                        "      ],\n"
                        "      \"onem2m:hasCommand\": {\n"
                        "        \"@id\": \"base:cmdPubUpdateImage\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:funcDescPubUpdateImage\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:funcPubUpdateManifest\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ControllingFunctionality\"\n"
                        "      ],\n"
                        "      \"onem2m:hasCommand\": {\n"
                        "        \"@id\": \"base:cmdPubUpdateManifest\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:funcDescPubUpdateManifest\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:funcRelayOff\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ControllingFunctionality\"\n"
                        "      ],\n"
                        "      \"onem2m:hasCommand\": {\n"
                        "        \"@id\": \"base:cmdRelayOff\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:funcDescRelayOff\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:funcRelayOn\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ControllingFunctionality\"\n"
                        "      ],\n"
                        "      \"onem2m:hasCommand\": {\n"
                        "        \"@id\": \"base:cmdRelayOn\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:funcDescRelayOn\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:hasSubStructure\",\n"
                        "      \"@type\": \"owl:AnnotationProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:inDpUpdateImage\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:InputDataPoint\"\n"
                        "      ],\n"
                        "      \"base:mqttTopic\": \"yang/update/image\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:inputUpdateImage\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OperationInput\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:propUpdateImage\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:descInputUpdateImage\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:input_1_AppId\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OperationInput\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:propAppID\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:descInputAppId\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:input_2_LinkOffset\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OperationInput\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:propLinkOffset\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:descInputLinkOffset\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:input_3_Hash\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OperationInput\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:propHash\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:descInputHash\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:input_4_Size\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OperationInput\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:propSize\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:descInputSize\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:input_5_Version\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OperationInput\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:propVersion\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:descInputVersion\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:input_6_OldVersion\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OperationInput\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:propOldVersion\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:descInputOldVersion\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:input_7_InnerSignature\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OperationInput\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:propInnerSignature\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:descInputInnerSignature\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:input_8_DeviceNonce\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OperationInput\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:propDeviceNonce\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:descInputDeviceNonce\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:input_9_OuterSignature\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OperationInput\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:propOuterSignature\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:descInputOuterSignature\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:mqttMethod\",\n"
                        "      \"@type\": \"owl:DatatypeProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:mqttTopic\",\n"
                        "      \"@type\": \"owl:DatatypeProperty\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:myDevice\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Device\"\n"
                        "      ],\n"
                        "      \"onem2m:hasFunctionality\": [\n"
                        "        {\n"
                        "          \"@id\": \"base:funcGetDeviceToken\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:funcGetMoisture\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:funcGetTemperature\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:funcPubUpdateImage\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:funcPubUpdateManifest\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:funcRelayOff\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:funcRelayOn\"\n"
                        "        }\n"
                        "      ],\n"
                        "      \"onem2m:hasService\": {\n"
                        "        \"@id\": \"base:servNetconf\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": [\n"
                        "        {\n"
                        "          \"@id\": \"base:deviceCategory\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:deviceDesc\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:deviceUuid\"\n"
                        "        }\n"
                        "      ]\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:opDescLedState\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataRestriction_pattern\": [\n"
                        "        \"error\",\n"
                        "        \"nothing to do\",\n"
                        "        \"successful\"\n"
                        "      ]\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:opDescState\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataRestriction_pattern\": [\n"
                        "        \"10 successful\",\n"
                        "        \"11 nothing to do\",\n"
                        "        \"12 error\",\n"
                        "        \"20 manifest not valid\",\n"
                        "        \"21 wrong app id\",\n"
                        "        \"22 invalid nonce\",\n"
                        "        \"23 outer sign invalid\",\n"
                        "        \"24 inner sign invalid\",\n"
                        "        \"25 invalid version number\",\n"
                        "        \"26 saveslot in use\",\n"
                        "        \"27 image too big\",\n"
                        "        \"28 image invalid\"\n"
                        "      ]\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:opGetDeviceToken\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Operation\"\n"
                        "      ],\n"
                        "      \"onem2m:exposesCommand\": {\n"
                        "        \"@id\": \"base:cmdGetDeviceToken\"\n"
                        "      },\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:uuidInput\"\n"
                        "      },\n"
                        "      \"onem2m:hasOperationState\": {\n"
                        "        \"@id\": \"base:opState\"\n"
                        "      },\n"
                        "      \"base:mqttMethod\": \"GET-DEVICE-TOKEN\",\n"
                        "      \"base:mqttTopic\": \"yang/update/token\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:opLedState\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OperationState\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataRestriction_pattern\": [\n"
                        "        \"ERROR\",\n"
                        "        \"NOOP\",\n"
                        "        \"OK\"\n"
                        "      ],\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:opDescLedState\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:opMqttPubUpdateImage\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Operation\"\n"
                        "      ],\n"
                        "      \"onem2m:exposesCommand\": {\n"
                        "        \"@id\": \"base:cmdPubUpdateImage\"\n"
                        "      },\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:inputUpdateImage\"\n"
                        "      },\n"
                        "      \"onem2m:hasInputDataPoint\": {\n"
                        "        \"@id\": \"base:inDpUpdateImage\"\n"
                        "      },\n"
                        "      \"onem2m:hasOperationState\": {\n"
                        "        \"@id\": \"base:opState\"\n"
                        "      },\n"
                        "      \"base:mqttMethod\": \"PUB-UPDATE-IMAGE\",\n"
                        "      \"base:mqttTopic\": \"yang/update\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:opMqttPubUpdateManifest\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Operation\"\n"
                        "      ],\n"
                        "      \"onem2m:exposesCommand\": {\n"
                        "        \"@id\": \"base:cmdPubUpdateManifest\"\n"
                        "      },\n"
                        "      \"onem2m:hasInput\": [\n"
                        "        {\n"
                        "          \"@id\": \"base:input_1_AppId\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_2_LinkOffset\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_3_Hash\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_4_Size\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_5_Version\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_6_OldVersion\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_7_InnerSignature\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_8_DeviceNonce\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:input_9_OuterSignature\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:uuidInput\"\n"
                        "        }\n"
                        "      ],\n"
                        "      \"onem2m:hasOperationState\": {\n"
                        "        \"@id\": \"base:opState\"\n"
                        "      },\n"
                        "      \"base:mqttMethod\": \"PUB-UPDATE-MANIFEST\",\n"
                        "      \"base:mqttTopic\": \"yang/update/manifest\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:opMqttRelayOff\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Operation\"\n"
                        "      ],\n"
                        "      \"onem2m:exposesCommand\": {\n"
                        "        \"@id\": \"base:cmdRelayOff\"\n"
                        "      },\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:uuidInput\"\n"
                        "      },\n"
                        "      \"onem2m:hasOperationState\": {\n"
                        "        \"@id\": \"base:opState\"\n"
                        "      },\n"
                        "      \"base:mqttMethod\": \"relayOff\",\n"
                        "      \"base:mqttTopic\": \"relay\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:opMqttRelayOn\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Operation\"\n"
                        "      ],\n"
                        "      \"onem2m:exposesCommand\": {\n"
                        "        \"@id\": \"base:cmdRelayOn\"\n"
                        "      },\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:uuidInput\"\n"
                        "      },\n"
                        "      \"onem2m:hasOperationState\": {\n"
                        "        \"@id\": \"base:opState\"\n"
                        "      },\n"
                        "      \"base:mqttMethod\": \"relayOn\",\n"
                        "      \"base:mqttTopic\": \"relay\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:opState\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OperationState\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataRestriction_pattern\": [\n"
                        "        \"10_OK\",\n"
                        "        \"11_NOOP\",\n"
                        "        \"12_ERROR\",\n"
                        "        \"20_MANIFEST-NOT-VALID\",\n"
                        "        \"21_WRONG-APP-ID\",\n"
                        "        \"22_INVALID-NONCE\",\n"
                        "        \"23_OUTER-SIGN-INVALID\",\n"
                        "        \"24_INNER-SIGN-INVALID\",\n"
                        "        \"25_INVALID-VERSIONNR\",\n"
                        "        \"26_SAVESLOT-IN-USE\",\n"
                        "        \"27_IMAGE-TOO-BIG\",\n"
                        "        \"28_IMAGE-INVALID\"\n"
                        "      ],\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:opDescState\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:outDpMoisture\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OutputDataPoint\"\n"
                        "      ],\n"
                        "      \"base:mqttTopic\": \"sensor/moisture/%s\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:outDpTemperature\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OutputDataPoint\"\n"
                        "      ],\n"
                        "      \"base:mqttTopic\": \"sensor/temperature/%s\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:propAppID\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ThingProperty\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataType\": {\n"
                        "        \"@id\": \"xsd:string\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:propDeviceNonce\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ThingProperty\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataType\": {\n"
                        "        \"@id\": \"xsd:int\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:propHash\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ThingProperty\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataType\": {\n"
                        "        \"@id\": \"xsd:string\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:propInnerSignature\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ThingProperty\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataType\": {\n"
                        "        \"@id\": \"xsd:hexBinary\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:propLinkOffset\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ThingProperty\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataType\": {\n"
                        "        \"@id\": \"xsd:int\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:propOldVersion\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ThingProperty\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataType\": {\n"
                        "        \"@id\": \"xsd:int\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:propOuterSignature\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ThingProperty\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataType\": {\n"
                        "        \"@id\": \"xsd:hexBinary\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:propSize\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ThingProperty\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataType\": {\n"
                        "        \"@id\": \"xsd:int\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:propUpdateImage\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ThingProperty\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataType\": {\n"
                        "        \"@id\": \"xsd:hexBinary\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:propVersion\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:ThingProperty\"\n"
                        "      ],\n"
                        "      \"onem2m:hasDataType\": {\n"
                        "        \"@id\": \"xsd:int\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:rdf:_1\",\n"
                        "      \"@type\": \"owl:ObjectProperty\",\n"
                        "      \"rdfs:subPropertyOf\": {\n"
                        "        \"@id\": \"rdfs:member\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:rdf:_2\",\n"
                        "      \"@type\": \"owl:ObjectProperty\",\n"
                        "      \"rdfs:subPropertyOf\": {\n"
                        "        \"@id\": \"rdfs:member\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:rdf:_3\",\n"
                        "      \"@type\": \"owl:ObjectProperty\",\n"
                        "      \"rdfs:subPropertyOf\": {\n"
                        "        \"@id\": \"rdfs:member\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:rdf:_4\",\n"
                        "      \"@type\": \"owl:ObjectProperty\",\n"
                        "      \"rdfs:subPropertyOf\": {\n"
                        "        \"@id\": \"rdfs:member\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:rdf:_5\",\n"
                        "      \"@type\": \"owl:ObjectProperty\",\n"
                        "      \"rdfs:subPropertyOf\": {\n"
                        "        \"@id\": \"rdfs:member\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:rdf:_6\",\n"
                        "      \"@type\": \"owl:ObjectProperty\",\n"
                        "      \"rdfs:subPropertyOf\": {\n"
                        "        \"@id\": \"rdfs:member\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:rdf:_7\",\n"
                        "      \"@type\": \"owl:ObjectProperty\",\n"
                        "      \"rdfs:subPropertyOf\": {\n"
                        "        \"@id\": \"rdfs:member\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:rdf:_8\",\n"
                        "      \"@type\": \"owl:ObjectProperty\",\n"
                        "      \"rdfs:subPropertyOf\": {\n"
                        "        \"@id\": \"rdfs:member\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:rdf:_9\",\n"
                        "      \"@type\": \"owl:ObjectProperty\",\n"
                        "      \"rdfs:subPropertyOf\": {\n"
                        "        \"@id\": \"rdfs:member\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:servGetDeviceToken\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Service\"\n"
                        "      ],\n"
                        "      \"onem2m:exposesFunctionality\": {\n"
                        "        \"@id\": \"base:funcGetDeviceToken\"\n"
                        "      },\n"
                        "      \"onem2m:hasOperation\": {\n"
                        "        \"@id\": \"base:opGetDeviceToken\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:servMoisture\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Service\"\n"
                        "      ],\n"
                        "      \"onem2m:exposesFunctionality\": {\n"
                        "        \"@id\": \"base:funcGetMoisture\"\n"
                        "      },\n"
                        "      \"onem2m:hasOutputDataPoint\": {\n"
                        "        \"@id\": \"base:outDpMoisture\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:servNetconf\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Service\"\n"
                        "      ],\n"
                        "      \"onem2m:exposesFunctionality\": [\n"
                        "        {\n"
                        "          \"@id\": \"base:funcRelayOff\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:funcRelayOn\"\n"
                        "        }\n"
                        "      ],\n"
                        "      \"onem2m:hasOperation\": [\n"
                        "        {\n"
                        "          \"@id\": \"base:opMqttRelayOff\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:opMqttRelayOn\"\n"
                        "        }\n"
                        "      ],\n"
                        "      \"onem2m:hasSubService\": [\n"
                        "        {\n"
                        "          \"@id\": \"base:servGetDeviceToken\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:servMoisture\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:servPubUpdateImage\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:servPubUpdateManifest\"\n"
                        "        },\n"
                        "        {\n"
                        "          \"@id\": \"base:servTemperature\"\n"
                        "        }\n"
                        "      ]\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:servPubUpdateImage\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Service\"\n"
                        "      ],\n"
                        "      \"onem2m:exposesFunctionality\": {\n"
                        "        \"@id\": \"base:funcPubUpdateImage\"\n"
                        "      },\n"
                        "      \"onem2m:hasOperation\": {\n"
                        "        \"@id\": \"base:opMqttPubUpdateImage\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:servPubUpdateManifest\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Service\"\n"
                        "      ],\n"
                        "      \"onem2m:exposesFunctionality\": {\n"
                        "        \"@id\": \"base:funcPubUpdateManifest\"\n"
                        "      },\n"
                        "      \"onem2m:hasOperation\": {\n"
                        "        \"@id\": \"base:opMqttPubUpdateManifest\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:servTemperature\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:Service\"\n"
                        "      ],\n"
                        "      \"onem2m:exposesFunctionality\": {\n"
                        "        \"@id\": \"base:funcGetTemperature\"\n"
                        "      },\n"
                        "      \"onem2m:hasOutputDataPoint\": {\n"
                        "        \"@id\": \"base:outDpTemperature\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:uuidInput\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"onem2m:OperationInput\"\n"
                        "      ],\n"
                        "      \"onem2m:hasInput\": {\n"
                        "        \"@id\": \"base:deviceUuid\"\n"
                        "      },\n"
                        "      \"onem2m:hasThingProperty\": {\n"
                        "        \"@id\": \"base:uuidYangDesc\"\n"
                        "      }\n"
                        "    },\n"
                        "    {\n"
                        "      \"@id\": \"base:uuidYangDesc\",\n"
                        "      \"@type\": [\n"
                        "        \"owl:NamedIndividual\",\n"
                        "        \"base:YangDescription\"\n"
                        "      ],\n"
                        "      \"onem2m:hasValue\": \"Target UUID for request\"\n"
                        "    }\n"
                        "  ]\n"
                        "}";

#endif /* ONTOLOGY_H_ */
